version: '3.9'

services:

  postgres-db:
    container_name: db

    image: postgres

    environment:
      POSTGRES_PASSWORD: manager
      POSTGRES_USER: manager
      POSTGRES_DB: travel_dev
    #      ALLOW_IP_RANGE: "0.0.0.0/0"

    ports:
      - 5432:5432

  tomcat-service:
    container_name: backend
    
    image: tomcat:9.0

    depends_on:
      - postgres-db

    environment:
      TOMCAT_USERNAME: tomcat
      TOMCAT_PASSWORD: tomcat
    
    volumes:
      - ./target/travel-storage-manager.war:/usr/local/tomcat/webapps/travel-storage-manager.war

    ports:
      - 8080:8080


